#ifndef GPUI_SYS_H
#define GPUI_SYS_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Operation completed successfully.
 */
#define gpui_GPUI_STATUS_OK 0

/**
 * A handle was negative, out of range, duplicated, or could not be allocated.
 */
#define gpui_GPUI_STATUS_INVALID_HANDLE -1

/**
 * The handle refers to the wrong kind of node for the requested operation.
 */
#define gpui_GPUI_STATUS_WRONG_NODE_KIND -2

/**
 * The node was already moved into another node by `gpui_add_child`.
 */
#define gpui_GPUI_STATUS_NODE_ABSENT -3

/**
 * An internal panic was caught before it could cross the C boundary.
 */
#define gpui_GPUI_STATUS_INTERNAL_PANIC -4

/**
 * The command buffer header magic or version did not match.
 */
#define gpui_GPUI_STATUS_BAD_BUFFER_VERSION -5

/**
 * The command buffer ended mid-field, or carried a truncated/oversized payload.
 */
#define gpui_GPUI_STATUS_TRUNCATED_BUFFER -6

/**
 * The command buffer named an opcode this build does not recognize.
 */
#define gpui_GPUI_STATUS_UNKNOWN_OPCODE -7

/**
 * `gpui_build_tree` finished without an `OP_SET_ROOT` designating a root.
 */
#define gpui_GPUI_STATUS_NO_ROOT -8

/**
 * Two or more nodes in the committed tree carry the same explicit key.
 */
#define gpui_GPUI_STATUS_DUPLICATE_KEY -9

/**
 * `gpui_update_text` found no node carrying the requested explicit key in the
 * committed tree for the view (the view may have no tree, or the key is absent
 * / belongs to a text node). Callers treat this as "fall back to a full
 * `gpui_build_tree` rebuild".
 */
#define gpui_GPUI_STATUS_KEY_NOT_FOUND -10

/**
 * The async injection queue is full (back-pressure): the producer should
 * retry later, coalesce, or drop — the library never blocks, discards, or
 * merges on its own (RFC 0002 §3.2).
 */
#define gpui_GPUI_STATUS_QUEUE_FULL -11

/**
 * The async injection payload exceeds the per-entry size limit.
 */
#define gpui_GPUI_STATUS_PAYLOAD_TOO_LARGE -12

/**
 * `gpui_input_set_text` was rejected because the input is mid-IME-composition
 * (a marked range is active). Overwriting the buffer would destroy the
 * composition the user sees; retry after the composition commits (RFC 0003
 * §3.5).
 */
#define gpui_GPUI_STATUS_BUSY_COMPOSING -13

/**
 * A command buffer carried a non-finite `f32` operand (NaN or ±infinity) for a
 * geometry field. Rejected at decode time so the value never reaches taffy:
 * measured behavior is that `f32::INFINITY` lays out to infinite bounds and an
 * infinite gap makes a sibling's width `NaN`, which then propagates silently
 * through paint and hit-testing (issue #75).
 */
#define gpui_GPUI_STATUS_INVALID_FLOAT -14

/**
 * The committed tree nests deeper than [`MAX_TREE_DEPTH`]. The three functions
 * that walk a tree (`render_node`, `collect_text_contents`, `update_keyed_text`)
 * are recursive; `stacker` grows the stack under them so a legitimate deep tree
 * still renders, but an unbounded one would grow until the allocator gives up.
 * Rejected before commit so the depth is capped once, at the boundary, rather
 * than separately in each walker (issue #74).
 */
#define gpui_GPUI_STATUS_DEPTH_EXCEEDED -15

/**
 * An `OP_TEXT_RUN` record is semantically invalid for the text node it
 * targets: out of bounds, not on a `char` boundary, overlapping/unsorted
 * against the previous run, or carrying unknown style flag bits. Rejection is
 * per-buffer (the tree is not committed) because gpui's run machinery panics
 * on ranges like these — `StyledText::compute_runs` subtracts range starts
 * and `with_runs` asserts the runs tile the text — so a lenient decoder would
 * trade a diagnosable status for a paint-time abort (issue #91).
 */
#define gpui_GPUI_STATUS_INVALID_TEXT_RUN -16

/**
 * Maximum number of queued injection entries (RFC 0002 §6-1). A full queue
 * fails `gpui_post_event` with `GPUI_STATUS_QUEUE_FULL` instead of blocking.
 */
#define gpui_INJECT_QUEUE_MAX_ENTRIES 1024

/**
 * Maximum payload size of a single injection entry, in bytes (RFC 0002
 * §6-1). Larger payloads fail with `GPUI_STATUS_PAYLOAD_TOO_LARGE`.
 */
#define gpui_INJECT_PAYLOAD_MAX_BYTES (1024 * 1024)

/**
 * Number of bytes `gpui_scroll_copy_state` writes: six little-endian f32
 * values (offset_x, offset_y, max_x, max_y, viewport_w, viewport_h).
 */
#define gpui_SCROLL_STATE_BYTES 24

/**
 * Push an event from any thread into the injection queue (RFC 0002 §3.1).
 * Non-blocking: the payload is copied under the queue lock and the call
 * returns immediately. The payload is opaque bytes — the library never
 * interprets it; framing is a contract between the producer and the MoonBit
 * `Event::Async` handler.
 *
 * `view` is the destination view id (index into `VIEWS`); a negative value
 * fails up front, an unknown one is dropped at drain time. `ptr` is borrowed
 * only for the duration of the call and copied internally (same contract as
 * every other FFI here). `len` may be 0: an entry can carry "something
 * happened" with no payload.
 *
 * Returns `GPUI_STATUS_OK`, `GPUI_STATUS_INVALID_HANDLE` (negative view, or
 * a null pointer with a nonzero length), `GPUI_STATUS_PAYLOAD_TOO_LARGE`, or
 * `GPUI_STATUS_QUEUE_FULL`. Posts made before any window starts are queued
 * and delivered by the first drain after startup.
 */
int32_t gpui_post_event(int32_t view, const uint8_t *ptr, int32_t len);

/**
 * Copy the text payload for a pending EVENT_TEXT dispatch.
 *
 * `token` is the index passed in `data_a`; `buf` must point to at least `len`
 * writable bytes (the `data_b` value). Returns the number of bytes written,
 * or a negative GPUI_STATUS_* on error. The payload is valid only during the
 * dispatch call that provided the token.
 */
int32_t gpui_event_copy_text(int32_t token, uint8_t *buf, int32_t len);

/**
 * Debug read-back: dump every text node's content from the committed tree for
 * `view` into `buf` as a sequence of `len u32 LE + utf8[len]` records (DFS
 * pre-order). Returns the total number of bytes written, or a negative
 * GPUI_STATUS_* on error. Used by the headless round-trip test (issue #34)
 * to verify MoonBit→C→Rust text fidelity without a GUI.
 */
int32_t gpui_debug_dump_text(int32_t view, uint8_t *buf, int32_t len);

/**
 * Cross-boundary ABI probe: echo `value` back unchanged.
 *
 * The whole bridge assumes MoonBit's native `Int` is ABI-compatible with
 * Rust's `i32` (callback envelope, command-buffer operands, status codes).
 * MoonBit's `main.mbt` type annotation anchors that at `moon check` time,
 * but nothing verifies the actual register/stack width across the boundary.
 * The headless round-trip test (issue #54, G23) sends boundary values
 * (`i32::MAX`, `i32::MIN`, 0, -1) through this probe on every build; any
 * width or sign-extension mismatch fails the build instead of corrupting
 * silently at runtime.
 */
int32_t gpui_abi_probe(int32_t value);

/**
 * Build and commit a tree for `view` from one command buffer. On any failure
 * the staging state is discarded and the previously committed tree is left
 * untouched.
 */
int32_t gpui_build_tree(int32_t view, const uint8_t *ptr, int32_t len);

/**
 * Update the text of a keyed node in the committed tree for `view` in place,
 * without rebuilding the tree (issue #10: measurement-justified incremental
 * update).
 *
 * `key_ptr`/`key_len` and `text_ptr`/`text_len` are UTF-8 byte slices (no NUL
 * terminator; the explicit lengths carry the size, matching how `OP_SET_KEY`
 * and `OP_TEXT` carry their strings). The function walks the retained
 * `VIEWS[view]` tree for the div whose `OP_SET_KEY` value equals `key` and
 * overwrites its first text child's content. The re-render still flows through
 * the existing dispatch→notify path: `dispatch` returns 1, Rust calls
 * `cx.notify()`, and `render_node` reads the now-updated `VIEWS[view]`.
 *
 * Returns `GPUI_STATUS_OK` on success. Returns `GPUI_STATUS_KEY_NOT_FOUND` when
 * the view has no committed tree or no keyed text node matches — the caller
 * (MoonBit) then falls back to a full `gpui_build_tree`. `GPUI_STATUS_INVALID_HANDLE`
 * for a negative view, `GPUI_STATUS_TRUNCATED_BUFFER` for a null/negative
 * pointer or length.
 */
int32_t gpui_update_text(int32_t view,
                         const uint8_t *key_ptr,
                         int32_t key_len,
                         const uint8_t *text_ptr,
                         int32_t text_len);

/**
 * Open a window rendering the committed tree for `view` (index into
 * `VIEWS`) and block in the GPUI event loop. A negative `view` fails with
 * `GPUI_STATUS_INVALID_HANDLE` before any GPUI startup.
 */
int32_t gpui_run_window(int32_t view, float width, float height);

extern void md_editor_benchmark_signpost_event(int32_t action_id);

int32_t gpui_run_window_benchmark(int32_t view,
                                  float width,
                                  float height,
                                  int32_t scenario,
                                  int32_t target,
                                  float stride,
                                  double document_load_ms);

/**
 * UTF-8 byte length of the committed content of `(view, input_id)`, for
 * buffer sizing before `gpui_input_copy_text`. Main-thread contract, same as
 * every other export called from inside `dispatch`.
 */
int32_t gpui_input_text_len(int32_t view, int32_t input_id);

/**
 * Copy the committed content of `(view, input_id)` into `buf` (up to `len`
 * bytes). Returns bytes written, or a negative status. Same contract as
 * `gpui_event_copy_text`.
 */
int32_t gpui_input_copy_text(int32_t view, int32_t input_id, uint8_t *buf, int32_t len);

/**
 * Replace the committed content of `(view, input_id)`; the caret moves to the
 * end. Rejected with `GPUI_STATUS_BUSY_COMPOSING` while an IME composition is
 * active (the marked text belongs to the IME, not the app). The write lands
 * in the mirror immediately (subsequent reads see it) and is applied to the
 * widget at its next prepaint.
 */
int32_t gpui_input_set_text(int32_t view, int32_t input_id, const uint8_t *ptr, int32_t len);

/**
 * Copy the mirrored scroll state of `(view, scroll_id)` into `buf` (issue
 * #89). Writes [`SCROLL_STATE_BYTES`] bytes: offset_x, offset_y, max_x,
 * max_y, viewport_w, viewport_h as little-endian f32. Offsets follow gpui's
 * scroll-space convention (≤ 0, more negative as content scrolls down/right);
 * max is the positive scrollable extent; viewport is the container's
 * laid-out size.
 *
 * Returns bytes written, `GPUI_STATUS_KEY_NOT_FOUND` when the pair has never
 * painted (or a rebuild removed it), or `GPUI_STATUS_INVALID_HANDLE` for a
 * negative view or a null/short buffer. Main-thread contract, same as the
 * other pull exports: call it during a dispatch.
 */
int32_t gpui_scroll_copy_state(int32_t view, int32_t scroll_id, uint8_t *buf, int32_t len);

#endif  /* GPUI_SYS_H */
